version: '3.9'

services:
  scrapyrealestate:
    image: mferark/scrapyrealestate:latest
    container_name: scrapyrealestate
    ports:
      - 8080:8080

    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #network_mode: host